version: '3.8'

services:
  backend:
    container_name: todo-backend
    build:
      context: ../backend
      dockerfile: ../devops-infra/docker/backend/Dockerfile
    ports:
      - "5000:5000"

  frontend:
    container_name: todo-frontend
    build:
      context: ../frontend
      dockerfile: ../devops-infra/docker/frontend/Dockerfile
    ports:
      - "3000:80"
